@extends('student.layout')
@section('content')
@if(!$selectedCourse)
<main class="content-wrap"><x-empty-state title="لا توجد مادة متاحة" description="المواد المرتبطة بحسابك ستظهر هنا."/></main>
@else
@php($course=$selectedCourse)
<section class="course-hero"><div class="content-wrap"><div class="course-hero-copy"><a class="breadcrumb" href="{{ ($preview??false)?(isset($previewCourseId)?route('admin.courses.curriculum',$previewCourseId):route('student.learning')):route('student.learning') }}"><x-icon name="arrow-right"/>{{ ($preview??false)?'العودة إلى محرر المنهج':'التعلّم الخاص بي' }}</a><span class="eyebrow">طب الأسنان · تعلّم بفهم</span><h1>{{ $course['title'] }}</h1><p>{{ $course['description'] }}</p><div class="course-meta"><span><x-icon name="play"/>{{ count($course['lessons']) }} دروس</span><span><x-icon name="clock"/>{{ (int)ceil(array_sum(array_column($course['lessons'],'duration'))/60) }} دقيقة</span><span>{{ $course['teacher'] }}</span></div></div><div class="course-hero-art cover-{{ $course['cover'] }}"><x-course-art :variant="$course['cover']"/></div></div></section>
<main class="content-wrap course-detail-grid"><div data-tabs>
<x-tabs :items="['overview'=>'نظرة عامة','curriculum'=>'المحتوى','attachments'=>'المرفقات']"/>
<section id="panel-overview" role="tabpanel" aria-labelledby="tab-overview" data-tab-panel="overview" class="tab-content"><h2>ما الذي ستتعلّمه؟</h2><div class="outcomes">@foreach(['فهم المفاهيم الأساسية وربطها ببعضها','تحديد التراكيب التشريحية بدقة','الربط بين الجانب النظري والتطبيق السريري','مراجعة منظّمة من خلال الملزمة المصوّرة'] as $outcome)<p><x-icon name="check"/>{{ $outcome }}</p>@endforeach</div><h2>عن هذه المادة</h2><p class="reading-copy">{{ $course['description'] }}</p><div class="teacher-block"><span class="avatar">س</span><div><strong>{{ $course['teacher'] }}</strong><p class="muted">شرح متسلسل · أمثلة توضيحية · مراجعة مستمرة</p></div></div></section>
<section id="panel-curriculum" role="tabpanel" aria-labelledby="tab-curriculum" data-tab-panel="curriculum" hidden class="tab-content"><div class="section-heading"><h2>محتوى المادة</h2><small class="muted">{{ count($course['lessons']) }} دروس</small></div>
<div class="curriculum-student-tree">@foreach($course['curriculum'] as $node)@include('student._curriculum-node',['node'=>$node])@endforeach</div>
@if(!count($course['lessons']))<x-empty-state title="الدروس قيد الإعداد" description="ستظهر الدروس هنا بعد نشرها."/>@endif</section>
<section id="panel-attachments" role="tabpanel" aria-labelledby="tab-attachments" data-tab-panel="attachments" hidden class="tab-content"><h2>مرفقات المادة</h2>@php($attachments=collect($course['lessons'])->flatMap(fn($lesson)=>$lesson['attachments']))@forelse($attachments as $attachment)<a class="lesson-attachment-link" href="{{ $attachment['url'] }}"><x-icon name="file"/><span><strong>{{ $attachment['name'] }}</strong><small class="muted">{{ $attachment['mime_type'] }} · {{ number_format($attachment['size_bytes']/1024,0) }} كيلوبايت</small></span><x-icon name="arrow-left"/></a>@empty<x-empty-state title="لا توجد مرفقات بعد" description="ستظهر مرفقات الدروس المنشورة هنا."/>@endforelse</section>
</div><aside class="course-enrollment card" data-course-id="{{ $course['id'] }}"><x-circular-progress :value="$course['percentage']"/><h3>رحلتك في هذه المادة</h3><p class="muted"><span data-course-percent>{{ $course['percentage'] }}٪ مكتمل</span> · تعلّم على إيقاعك</p>@if(count($course['lessons']))<a class="btn primary full" data-course-continue href="{{ (collect($course['lessons'])->firstWhere('completed',false) ?? $course['lessons'][0])['url'] }}">متابعة التعلّم<x-icon name="arrow-left"/></a>@endif<hr><p><x-icon name="play"/>دروس قصيرة ومركّزة</p><p><x-icon name="file"/>محتوى منظّم للمراجعة</p><p><x-icon name="chart"/>تتبّع تقدمك في كل خطوة</p></aside></main>
@endif
@endsection
