@extends('student.layout')
@section('content')
<main class="content-wrap learning-page">
<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span>رحلتك نحو معرفة أعمق</div><h1>التعلّم الخاص بي<span class="heading-dot">.</span></h1><p class="muted">أهلاً {{ ($preview ?? false)?'أحمد':auth('student')->user()?->name }}، خطوة جديدة اليوم تقرّبك من هدفك.</p></div><a class="btn subtle" href="{{ ($preview??false)?route('student.progress'):route('student.progress') }}"><x-icon name="chart"/>نظرة على تقدّمي<x-icon name="arrow-left"/></a></div>
@if(count($courseCards))
@php($resumeCourse = $resumeCourse ?? collect($courseCards)->first(fn($course)=>collect($course['lessons'])->contains(fn($lesson)=>$lesson['position_seconds']>0)) ?? $courseCards[0])
@php($resumeLesson = $resumeLesson ?? collect($resumeCourse['lessons'])->first(fn($lesson)=>$lesson['position_seconds']>0) ?? collect($resumeCourse['lessons'])->firstWhere('completed', false) ?? ($resumeCourse['lessons'][0]??null))
@if($resumeLesson)
<section class="continue-banner" data-resume-banner>
<div class="banner-copy"><span class="banner-kicker"><span class="status-dot"></span>تابع من حيث توقفت</span><h2 data-resume-course>{{ $resumeCourse['title'] }}</h2><p data-resume-title>{{ $resumeLesson['title'] }}</p><div class="banner-progress"><x-progress-bar :value="$resumeCourse['percentage']"/><span data-resume-percent>{{ $resumeCourse['percentage'] }}٪ من المادة مكتمل</span></div><div class="banner-actions"><a class="btn primary" data-resume-link href="{{ $resumeLesson['url'] }}"><x-icon name="play"/>متابعة من {{ gmdate('i:s', (int) ($resumeLesson['position_seconds'] ?? 0)) }}</a><span><x-icon name="clock"/><span data-resume-time>{{ $resumeLesson['progress_percent'] ?? 0 }}٪ من الدرس</span></span></div></div>
<div class="banner-illustration"><div class="illustration-caption"><span>THE ART OF</span><strong>UNDERSTANDING.</strong><span>كل تفصيل، بداية فهم جديد.</span></div><x-course-art :variant="$resumeCourse['cover']"/><div class="annotation"><i></i>تعلّم. افهم. طبّق.</div></div>
</section>@endif
<section class="learning-summary" aria-label="ملخص رحلتك"><span><x-icon name="book"/><strong>{{ count($courseCards) }}</strong> مواد في مكتبتك</span><span><x-icon name="check"/><strong data-total-completed>{{ collect($courseCards)->sum(fn($course)=>count(array_filter($course['lessons'],fn($lesson)=>$lesson['completed']))) }}</strong> دروس أنجزتها</span><span><x-icon name="clock"/><strong data-total-minutes>٠</strong> دقيقة تعلّم</span><span class="summary-note">كل درس، خطوة للأمام.</span></section>
@endif
<section class="courses-section"><div class="section-heading"><div><h2>مكتبة موادك</h2><p class="muted">معرفة منظّمة، وتقدّم يمكنك رؤيته.</p></div><span class="badge">{{ count($courseCards) }} مواد</span></div><div class="library-toolbar"><nav class="tabs" aria-label="تصفية المواد">@foreach(['all'=>'كل المواد','in-progress'=>'قيد المتابعة','completed'=>'المكتملة'] as $key=>$label)<button type="button" data-course-filter="{{ $key }}" @class(['active'=>$loop->first]) aria-pressed="{{ $loop->first?'true':'false' }}">{{ $label }}</button>@endforeach</nav>@if(!($preview ?? false))<label class="sort-select"><span class="muted">المرحلة:</span><select data-grade-level-filter aria-label="تصفية حسب المرحلة الصفية"><option value="">كل المراحل</option>@foreach(collect($courseCards)->whereNotNull('grade_level_id')->unique('grade_level_id') as $gradeCourse)<option value="{{ $gradeCourse['grade_level_id'] }}">{{ $gradeCourse['grade_level_name'] }}</option>@endforeach</select></label>@endif<label class="sort-select"><span class="muted">الترتيب:</span><select data-course-sort aria-label="ترتيب المواد"><option value="default">المضافة حديثاً</option><option value="title">حسب الاسم</option><option value="progress">حسب التقدّم</option></select></label></div>
@if(count($courseCards))<div class="course-grid" data-course-grid>@foreach($courseCards as $course)<x-course-card :course="$course"/>@endforeach</div><x-empty-state class="student-filter-empty" hidden title="لا توجد مواد مطابقة" description="جرّب كلمة أخرى أو اختر كل المواد."/>
@else<x-empty-state title="مكتبتك بانتظار أول مادة" description="عند ربط المواد بحسابك، ستجدها هنا جاهزة للتعلّم."/>@endif</section>
<section class="learning-note"><div class="note-icon"><x-icon name="book"/></div><div><h3>القليل المستمر يصنع فرقاً كبيراً</h3><p class="muted">خصّص وقتاً قصيراً كل يوم. تعلّم بتركيز، ودوّن أفكارك، ثم عُد لتراجع ما تعلّمته.</p></div><span class="note-decoration" aria-hidden="true">✧</span></section>
</main>
@endsection
