@extends('student.layout')

@section('content')
<main class="lesson-page" data-lesson-page data-lesson-payload="{{ json_encode($lessonData) }}">
    <div class="lesson-topbar"><a href="{{ $lessonData['course_url'] }}" class="lesson-back"><span aria-hidden="true">→</span> <span>العودة للمادة</span></a><span class="lesson-topbar-divider"></span><strong>{{ $lessonData['course_title'] }}</strong><div class="lesson-overall-progress"><span class="lesson-progress-ring" data-lesson-progress-ring><b data-lesson-percent>0%</b></span><span>تقدمك في المادة</span></div><button type="button" class="btn small curriculum-toggle" data-curriculum-toggle aria-expanded="true" aria-controls="lesson-curriculum">☷ <span>محتوى المادة</span></button></div>
    <button type="button" class="curriculum-backdrop" data-curriculum-backdrop aria-label="إغلاق محتوى المادة" tabindex="-1"></button>
    <div class="lesson-workspace">
        <div class="lesson-main">
            @if(!empty($lessonData['stream_url']))
                <x-video-player :lesson="$lessonData" :preview="$preview ?? false" />
            @elseif($lessonData['type']==='video' || in_array($lessonData['video_status'] ?? '', ['queued', 'processing', 'failed']))
                <section class="video-not-ready" data-video-pending-status="{{ $lessonData['video_status'] ?? 'not_uploaded' }}" data-video-pending-url="{{ $lessonData['video_status_url'] ?? '' }}" data-lesson-id="{{ $lessonData['id'] }}" role="status"><span class="eyebrow">{{ ['queued' => 'الفيديو بانتظار المعالجة', 'processing' => 'يجري تجهيز الفيديو', 'failed' => 'تعذّر تجهيز الفيديو'][$lessonData['video_status'] ?? ''] ?? 'لم يُرفع فيديو لهذا الدرس بعد' }}</span><h2>سيظهر الدرس هنا عند جاهزية الفيديو</h2><p>يمكنك متابعة بقية محتوى المادة الآن.</p></section>
            @else
                <article class="lesson-reading-content lesson-content-preview" data-text-protected>@if($lessonData['body_html']){!! \App\Support\SafeRichText::sanitize($lessonData['body_html']) !!}@else<p>{{ $lessonData['description'] ?: 'محتوى الدرس ومرفقاته.' }}</p>@endif</article>
            @endif
            <div class="lesson-navigation"><div>@if($lessonData['previous_url'])<a class="lesson-nav-link" href="{{ $lessonData['previous_url'] }}"><span aria-hidden="true">→</span> الدرس السابق</a>@else<span class="lesson-nav-link muted">أول درس في رحلتك</span>@endif</div>@if(!empty($lessonData['stream_url']))<button type="button" class="btn small" data-complete-lesson aria-pressed="false"><span aria-hidden="true">✓</span> <span data-complete-label>تحديد كمكتمل</span></button>@endif<div>@if($lessonData['next_url'])<a class="lesson-nav-link" href="{{ $lessonData['next_url'] }}">الدرس التالي <span aria-hidden="true">←</span></a>@else<a class="lesson-nav-link" href="{{ $lessonData['course_url'] }}">العودة للمادة <span aria-hidden="true">←</span></a>@endif</div></div>
            <div class="lesson-details">
                <div class="lesson-title-row"><div><span class="eyebrow">{{ $lessonData['course_title'] }}</span><h1>{{ $lessonData['title'] }}</h1><p class="muted">د. سليم أحمد <span aria-hidden="true">·</span> {{ (int) ceil($lessonData['duration'] / 60) }} دقيقة</p></div><button type="button" class="btn playlist-button" data-player-playlist aria-pressed="false"><span aria-hidden="true">＋</span><span data-playlist-label>قائمة التشغيل</span></button></div>
                <div class="tabs lesson-tabs" role="tablist" aria-label="تفاصيل الدرس"><button type="button" id="lesson-tab-overview" class="active" role="tab" aria-selected="true" aria-controls="lesson-panel-overview" data-lesson-tab="overview">نظرة عامة</button><button type="button" id="lesson-tab-transcript" role="tab" aria-selected="false" aria-controls="lesson-panel-transcript" data-lesson-tab="transcript" tabindex="-1">النص</button><button type="button" id="lesson-tab-attachments" role="tab" aria-selected="false" aria-controls="lesson-panel-attachments" data-lesson-tab="attachments" tabindex="-1">المرفقات <span class="tab-count">{{ count($lessonData['attachments']) }}</span></button><button type="button" id="lesson-tab-notes" role="tab" aria-selected="false" aria-controls="lesson-panel-notes" data-lesson-tab="notes" tabindex="-1">ملاحظاتي</button></div>
                <section id="lesson-panel-overview" class="lesson-panel" role="tabpanel" aria-labelledby="lesson-tab-overview" data-lesson-panel="overview"><h2>عن هذا الدرس</h2><p>{{ $lessonData['description'] ?: 'شرح ومادة الدرس.' }}</p>@if($lessonData['body_html'])<div class="lesson-reading-content" data-text-protected>{!! \App\Support\SafeRichText::sanitize($lessonData['body_html']) !!}</div>@endif<p class="lesson-keyboard-hint">اختصارات المشغّل: المسافة للتشغيل والإيقاف، والسهم الأيسر للتقديم والأيمن للتأخير.</p></section>
                <section id="lesson-panel-transcript" class="lesson-panel" role="tabpanel" aria-labelledby="lesson-tab-transcript" data-lesson-panel="transcript" hidden><h2>نص الدرس</h2><div class="lesson-reading-content" data-text-protected>{!! \App\Support\SafeRichText::sanitize($lessonData['body_html']) !!}</div></section>
                <section id="lesson-panel-attachments" class="lesson-panel" role="tabpanel" aria-labelledby="lesson-tab-attachments" data-lesson-panel="attachments" hidden><h2>مرفقات الدرس</h2><p class="muted">تُقدّم الملفات من التخزين الخاص بعد التحقق من صلاحية الحساب.</p><div class="lesson-attachments-list">@forelse($lessonData['attachments'] as $attachment)<a href="{{ $attachment['url'] }}" class="lesson-attachment-link"><x-icon name="file"/><span><strong>{{ $attachment['name'] }}</strong><small>{{ $attachment['mime_type'] }} · {{ number_format($attachment['size_bytes']/1024,0) }} KB</small></span><span>عرض محمي</span></a>@empty<p class="muted">لا توجد مرفقات لهذا الدرس.</p>@endforelse</div></section>
                <section id="lesson-panel-notes" class="lesson-panel" role="tabpanel" aria-labelledby="lesson-tab-notes" data-lesson-panel="notes" hidden><h2>دفتر ملاحظاتك</h2><p class="muted">أضف فكرة مهمة واربطها بوقت الدرس. تُحفظ ملاحظاتك على هذا الجهاز.</p><form data-note-form><label class="sr-only" for="lesson-note">ملاحظة جديدة</label><textarea id="lesson-note" name="note" rows="3" maxlength="2000" placeholder="ما الفكرة التي تريد تذكّرها؟" required></textarea><div class="note-form-actions"><small class="muted">عند <span data-note-time dir="ltr">00:00</span></small><button type="submit" class="btn primary small">حفظ الملاحظة</button></div></form><div class="lesson-notes-list" data-notes-list></div><p data-notes-empty class="notes-empty">لا توجد ملاحظات بعد. أول فكرة تستحق أن تُكتب.</p></section>
            </div>
        </div>
        <x-curriculum-sidebar :curriculum="$curriculum" :tree="$selectedCourse['curriculum'] ?? []" :current-id="$lessonData['id']" />
    </div>
    <div class="lesson-toast" data-lesson-toast role="status" hidden></div>
</main>
@endsection
