@extends('student.layout')
@section('content')
@php($preview = $preview ?? false)
<main class="content-wrap"><div class="page-heading"><div><span class="eyebrow">خطتك التالية</span><h1>قائمة التشغيل</h1><p class="muted">أنشئ قوائمك، وأضف الدروس ورتبها حسب خطتك.</p></div></div>
<section class="card"><form method="post" action="{{ route('student.playlists.create') }}">@csrf<label>قائمة جديدة <input name="name" required maxlength="100" placeholder="مثال: مراجعة التشريح"></label><button class="btn">إنشاء قائمة</button></form><h2>أضف درساً</h2><form method="post" action="{{ route('student.playlist-items.store') }}">@csrf<label>الدرس<select name="lesson_id" required>@foreach($courses as $course)<optgroup label="{{ $course->title }}">@foreach($course->lessons as $lesson)<option value="{{ $lesson->id }}">{{ $lesson->title }}</option>@endforeach</optgroup>@endforeach</select></label><label>القائمة<select name="playlist_id">@foreach($playlists as $list)<option value="{{ $list->id }}" @selected($playlist->id===$list->id)>{{ $list->name }}</option>@endforeach</select></label><button class="btn">إضافة</button></form></section>
<section class="card"><form method="get"><label>عرض قائمة<select name="playlist_id" data-submit-on-change>@foreach($playlists as $list)<option value="{{ $list->id }}" @selected($playlist->id===$list->id)>{{ $list->name }}</option>@endforeach</select></label></form><h2>{{ $playlist->name }}</h2>@forelse($playlist->items as $item)<article class="playlist-row" data-playlist-item="{{ $item->id }}"><div><a href="{{ route('student.lesson.show',$item->lesson) }}"><b>{{ $item->lesson->title }}</b></a><p>{{ $item->lesson->course->title }}</p></div><form method="post" action="{{ route('student.playlists.order',$playlist) }}" data-order-form>@csrf @method('PATCH')@foreach($playlist->items as $ordered)<input type="hidden" name="item_ids[]" value="{{ $ordered->id }}">@endforeach<button type="button" class="btn btn-secondary" data-move="-1" aria-label="نقل للأعلى">↑</button><button type="button" class="btn btn-secondary" data-move="1" aria-label="نقل للأسفل">↓</button></form><form method="post" action="{{ route('student.playlist-items.destroy',$item) }}" data-confirm="حذف الدرس من القائمة؟">@csrf @method('DELETE')<button class="btn btn-secondary">حذف</button></form></article>@empty<p class="muted">أضف أول درس إلى هذه القائمة.</p>@endforelse</section>
<script nonce="{{ $cspNonce ?? '' }}">document.querySelectorAll('[data-order-form] [data-move]').forEach(button=>button.addEventListener('click',()=>{const rows=[...document.querySelectorAll('[data-playlist-item]')],row=button.closest('[data-playlist-item]'),index=rows.indexOf(row),next=index+Number(button.dataset.move);if(next<0||next>=rows.length)return;rows.splice(index,1);rows.splice(next,0,row);const ids=rows.map(item=>item.dataset.playlistItem);rows.forEach(item=>item.querySelectorAll('[data-order-form] input[name="item_ids[]"]').forEach((input,i)=>input.value=ids[i]));rows.forEach(item=>item.parentNode.append(item));row.querySelector('[data-order-form]').requestSubmit()}));</script>
</main>
@endsection
