@extends('admin.layout', ['title' => $lesson->exists ? 'تحرير المحاضرة' : 'إضافة محاضرة'])
@section('content')
<div class="admin-head"><div><span class="eyebrow">{{ $course->gradeLevel?->name }} ← {{ $course->title }}</span><h1>{{ $lesson->exists ? 'تحرير المحاضرة' : 'إضافة محاضرة' }}</h1><p class="muted">النص والفيديو والمرفقات، في مساحة واحدة.</p></div><div class="admin-head-actions">@if($lesson->exists)<a class="btn" href="{{ route('admin.courses.preview', ['course'=>$course,'lesson'=>$lesson->id]) }}"><x-icon name="eye"/> معاينة المحاضرة</a>@endif<a class="btn" href="{{ route('admin.lessons.index', ['grade_level_id'=>$course->grade_level_id,'course_id'=>$course->id]) }}">عودة للمحاضرات</a></div></div>
<div class="lecture-editor-grid">
    <form id="lecture-content-form" class="admin-form lecture-content-form" method="post" action="{{ $lesson->exists ? route('admin.lessons.update', $lesson) : route('admin.courses.lessons.store', $course) }}">
        @csrf @if($lesson->exists)@method('PUT')@endif
        <label for="lecture-title">اسم المحاضرة</label><input id="lecture-title" name="title" value="{{ old('title', $lesson->title) }}" placeholder="مثلاً: مقدمة في تشريح الأسنان" maxlength="180" required autofocus>
        <label for="lecture-description">وصف مختصر <span class="muted">(اختياري)</span></label><textarea id="lecture-description" name="description" rows="2" maxlength="12000" placeholder="ما الذي سيتعلّمه الطالب؟">{{ old('description', $lesson->description) }}</textarea>
        <div class="lecture-section-heading"><x-icon name="edit"/><h2>محتوى المحاضرة</h2><span class="muted" data-rich-count>٠ حرف</span></div>
        <div class="rich-text-toolbar" role="toolbar" aria-label="تنسيق نص المحاضرة">
            <button type="button" data-rich-command="bold" title="عريض" aria-label="عريض"><b>B</b></button><button type="button" data-rich-command="italic" title="مائل" aria-label="مائل"><i>I</i></button><button type="button" data-rich-command="underline" title="تسطير" aria-label="تسطير"><u>U</u></button>
            <button type="button" data-rich-command="formatBlock" data-rich-argument="h2" title="عنوان رئيسي">H2</button><button type="button" data-rich-command="formatBlock" data-rich-argument="h3" title="عنوان فرعي">H3</button><button type="button" data-rich-command="formatBlock" data-rich-argument="p" title="فقرة">¶</button>
            <button type="button" data-rich-command="insertUnorderedList" title="قائمة نقطية" aria-label="قائمة نقطية"><x-icon name="list"/></button><button type="button" data-rich-command="insertOrderedList" title="قائمة مرقمة" aria-label="قائمة مرقمة">١.٢.</button><button type="button" data-rich-command="formatBlock" data-rich-argument="blockquote" title="اقتباس" aria-label="اقتباس">❝</button>
            <button type="button" data-rich-command="createLink" title="إضافة رابط" aria-label="إضافة رابط"><x-icon name="link"/></button><button type="button" data-rich-command="unlink" title="إزالة الرابط" aria-label="إزالة الرابط"><x-icon name="ban"/></button><button type="button" data-rich-command="undo" title="تراجع" aria-label="تراجع">↶</button><button type="button" data-rich-command="redo" title="إعادة" aria-label="إعادة">↷</button><button type="button" data-rich-command="removeFormat" title="إزالة التنسيق" aria-label="إزالة التنسيق">Tx</button>
        </div>
        <div class="rich-text-surface lecture-rich-surface" contenteditable="true" role="textbox" aria-multiline="true" aria-label="نص المحاضرة" data-rich-editor data-placeholder="اكتب شرح المحاضرة، وأضف العناوين والقوائم والروابط…">{!! \App\Support\SafeRichText::sanitize(old('body_html', $lesson->body_html)) !!}</div>
        <textarea name="body_html" hidden data-rich-value>{{ old('body_html', $lesson->body_html) }}</textarea>
        <noscript><p>لتعديل النص المنسق فعّل JavaScript في المتصفح.</p></noscript>
        <details class="lecture-advanced"><summary><x-icon name="settings"/> خيارات إضافية</summary><label>نوع المحتوى الأساسي<select name="type"><option value="text" @selected(old('type',$lesson->type)==='text')>شرح نصي (يمكن إضافة فيديو وملفات)</option><option value="video" @selected(old('type',$lesson->type)==='video')>فيديو مع شرح ومرفقات</option><option value="file" @selected(old('type',$lesson->type)==='file')>ملفات مع شرح</option>@if(!in_array($lesson->type,['text','video','file',null],true))<option value="{{ $lesson->type }}" selected>مستند</option>@endif</select></label><label>المدة بالثواني <span class="muted">(تُحدّث تلقائياً بعد تجهيز الفيديو)</span><input type="number" min="0" max="86400" name="duration_seconds" value="{{ old('duration_seconds', $lesson->duration_seconds) }}"></label><label>ترتيب المحاضرة<input type="number" min="0" name="position" value="{{ old('position', $lesson->position) }}"></label></details>
        <div class="lecture-save-bar"><span class="muted" data-rich-save-status>احفظ التغييرات قبل المغادرة</span><button class="btn primary"><x-icon name="save"/> {{ $lesson->exists ? 'حفظ المحاضرة' : 'إنشاء المحاضرة وإضافة الوسائط' }}</button></div>
    </form>
    <aside class="lecture-editor-aside">
        <section class="admin-form lecture-publish" data-publication-fields><div class="lecture-section-heading"><x-icon name="eye"/><h2>النشر</h2></div><label>حالة المحاضرة<select name="publication_status" form="lecture-content-form" data-publication-status><option value="draft" @selected(old('publication_status',$lesson->publication_status)==='draft')>مسودة — للتحضير</option><option value="published" @selected(old('publication_status',$lesson->publication_status)==='published')>منشورة — تظهر للطلاب</option><option value="scheduled" @selected(old('publication_status',$lesson->publication_status)==='scheduled')>نشر في موعد محدد</option></select></label><label data-scheduled-field>موعد النشر<input type="datetime-local" name="scheduled_at" form="lecture-content-form" value="{{ old('scheduled_at', $lesson->scheduled_at?->format('Y-m-d\TH:i')) }}"></label><p class="muted">{{ $course->isVisibleToStudents() ? 'تظهر المحاضرة المنشورة لطلاب هذه المادة.' : 'المادة غير منشورة حالياً. انشر المادة أيضاً ليتمكن الطلاب من رؤية محاضراتها.' }}</p>@unless($course->isVisibleToStudents())<a class="text-link" href="{{ route('admin.courses.edit',$course) }}">إعدادات نشر المادة</a>@endunless</section>
        <section class="admin-form lecture-media"><div class="lecture-section-heading"><x-icon name="play"/><h2>الفيديو</h2></div>@if($lesson->exists)@include('admin.lessons._video', ['lesson'=>$lesson])@else<p class="muted">احفظ اسم المحاضرة ونصها أولاً؛ سيظهر هنا رفع الفيديو مع متابعة تقدّمه.</p>@endif</section>
        <section class="admin-form lecture-media"><div class="lecture-section-heading"><x-icon name="file"/><h2>الملفات والصور</h2></div>@if($lesson->exists)<form class="attachment-upload-form" method="post" enctype="multipart/form-data" action="{{ route('admin.lessons.attachments.store',$lesson) }}" data-lecture-attachments>@csrf<label>أضف PDF أو صوراً<input type="file" name="attachments[]" accept="application/pdf,image/jpeg,image/png,image/webp" multiple required></label><p class="muted" data-attachment-selection>يمكنك اختيار عدة ملفات معاً.</p><button class="btn small"><x-icon name="upload"/> رفع المرفقات</button></form><ul class="private-attachments">@forelse($lesson->attachments as $attachment)<li><a href="{{ route('admin.lesson-attachments.show',$attachment) }}"><x-icon name="file"/> {{ $attachment->original_name }}</a><form method="post" action="{{ route('admin.lesson-attachments.destroy',$attachment) }}" data-confirm="حذف هذا المرفق؟">@csrf @method('DELETE')<button class="icon-btn" aria-label="حذف {{ $attachment->original_name }}"><x-icon name="trash"/></button></form></li>@empty<li class="muted">لا توجد مرفقات بعد.</li>@endforelse</ul>@else<p class="muted">بعد إنشاء المحاضرة يمكنك إضافة الملفات والصور هنا.</p>@endif</section>
    </aside>
</div>
@if($lesson->exists)<details class="lecture-advanced"><summary>حذف المحاضرة</summary><form method="post" action="{{ route('admin.lessons.destroy',$lesson) }}" data-confirm="حذف المحاضرة وتقدم الطلاب المرتبط بها؟">@csrf @method('DELETE')<button class="btn">حذف المحاضرة</button></form></details>@endif
@endsection
